Chyam/10 restructure repo
Azure/azure-openai-workshop pull request #11
Opened 2023-03-23 12:35 UTC by ryubidragonfire

Restructure to:
── AUTHORS.md
├── CODE_OF_CONDUCT.md
├── LICENSE
├── README.md
├── README_old.md
├── SECURITY.md
├── SUPPORT.md
├── archive
│   └── Labs
│       └── Clustering-and-Embedding
├── documentation
│   └── lease_extraction
├── fundamentals
│   ├── document_analysis
│   └── large_data
├── quick_start
├── requirements.txt
├── solution_accelarators
└── use_cases
    ├── call_center
    ├── generate_podcast_synopsis
    └── give_an_appropriate_name

Kept almost all content, except arhive/labs/clustering-and-embedding/ due to duplications. Welcome author to come forward for integration. 

This is not perfect, may require another iterations to refine.

2023-03-23 12:39 UTC, ryubidragonfire commented
@jimmyliao @aldelar @aschauhan22 @louis-li @brandoncowenms I believe you are contributed to the repo. 

As per the v-team decision to reorganise the repo, I have given the first go. 

This is not perfect yet, however, it will servce as the first iteration. 

Please review:
- overall structure
- your specific contributions, to try to fit the overal format as much as possible. 
   - consider create a PR on this branch to work on your specific folder

Thank you for your collaboration.

2023-03-23 22:45 UTC, aldelar commented
Overall looks good @ryubidragonfire with some notes here:

1) Broken image link in the doc here: https://github.com/Azure/azure-openai-workshop/blob/chyam/10-restructure-repo/use_cases/give_an_appropriate_name/README.md

2) https://github.com/Azure/azure-openai-workshop/tree/chyam/10-restructure-repo/use_cases/give_an_appropriate_name

Should the content of that folder be split between 'quick starts' and then the rest moved under a new folder in 'fundamentals' called 'leveraging_langchain' or 'build_with_langchain' as a few are langchain related?

@louis-li feedback on this?

3) https://github.com/Azure/azure-openai-workshop/tree/chyam/10-restructure-repo/use_cases/call_center
Should move the .wav files to a 'data' folder in this location to be consistent with the rest of the repo.

4) https://github.com/Azure/azure-openai-workshop/tree/chyam/10-restructure-repo/solution_accelarators
directory name is misspelled: 'accelarators' instead of 'accelerators'

2023-03-23 22:46 UTC, aldelar requested changes
See my comments in the PR.
Would be nice to take care of these things if you can tomorrow before we merge this?

2023-03-24 02:26 UTC, louis-li commented
Thanks Chew-Yean for your hard work. 

There are a few minor issues we can update later:
1. https://github.com/Azure/azure-openai-workshop/blob/chyam/10-restructure-repo/archive/Labs/Clustering-and-Embedding/Lab-clustering-embeddings-themes.ipynb

The image should be updated or removed - We cannot use OpenAI logo.

2. https://github.com/Azure/azure-openai-workshop/blob/chyam/10-restructure-repo/fundamentals/document_analysis/README.md

Some reference links are same as the ones in the READM.md in root folder

3. https://github.com/Azure/azure-openai-workshop/blob/chyam/10-restructure-repo/quick_start/README.md

The message should be updated. The Environmental variable section no longer apply.

2023-03-24 02:33 UTC, louis-li commented
> Overall looks good @ryubidragonfire with some notes here:
> 
> 1. Broken image link in the doc here: https://github.com/Azure/azure-openai-workshop/blob/chyam/10-restructure-repo/use_cases/give_an_appropriate_name/README.md
> 2. https://github.com/Azure/azure-openai-workshop/tree/chyam/10-restructure-repo/use_cases/give_an_appropriate_name
> 
> Should the content of that folder be split between 'quick starts' and then the rest moved under a new folder in 'fundamentals' called 'leveraging_langchain' or 'build_with_langchain' as a few are langchain related?
> 
> @louis-li feedback on this?

In this folder, only first notebook is not langchain related. I like the idea of naming the folder 'work_with_langchain' or something similar. We can move the first notebook to another suitable place.

2023-03-28 12:21 UTC, ryubidragonfire commented
> Overall looks good @ryubidragonfire with some notes here:
> 
> 1. Broken image link in the doc here: https://github.com/Azure/azure-openai-workshop/blob/chyam/10-restructure-repo/use_cases/give_an_appropriate_name/README.md [done]
> 2. https://github.com/Azure/azure-openai-workshop/tree/chyam/10-restructure-repo/use_cases/give_an_appropriate_name
> 
> Should the content of that folder be split between 'quick starts' and then the rest moved under a new folder in 'fundamentals' called 'leveraging_langchain' or 'build_with_langchain' as a few are langchain related? [done]
> 
> @louis-li feedback on this?
> 
> 3. https://github.com/Azure/azure-openai-workshop/tree/chyam/10-restructure-repo/use_cases/call_center
>    Should move the .wav files to a 'data' folder in this location to be consistent with the rest of the repo. [done]
> 4. https://github.com/Azure/azure-openai-workshop/tree/chyam/10-restructure-repo/solution_accelarators
>    directory name is misspelled: 'accelarators' instead of 'accelerators'  [done]

2023-03-28 12:22 UTC, ryubidragonfire commented
click wrong button

2023-03-28 12:24 UTC, ryubidragonfire commented
> > Overall looks good @ryubidragonfire with some notes here:
> > 
> > 1. Broken image link in the doc here: https://github.com/Azure/azure-openai-workshop/blob/chyam/10-restructure-repo/use_cases/give_an_appropriate_name/README.md
> > 2. https://github.com/Azure/azure-openai-workshop/tree/chyam/10-restructure-repo/use_cases/give_an_appropriate_name
> > 
> > Should the content of that folder be split between 'quick starts' and then the rest moved under a new folder in 'fundamentals' called 'leveraging_langchain' or 'build_with_langchain' as a few are langchain related?
> > @louis-li feedback on this?
> 
> In this folder, only first notebook is not langchain related. I like the idea of naming the folder 'work_with_langchain' or something similar. We can move the first notebook to another suitable place. [done]

2023-03-28 12:25 UTC, ryubidragonfire commented
> See my comments in the PR. Would be nice to take care of these things if you can tomorrow before we merge this?

[done]

2023-03-28 12:29 UTC, ryubidragonfire commented
Thank you for the comments. 
@louis-li @aldelar  please kindly re-review. I have a small window of time at night my time, if there are further comments before merge. I will have little time for the rest of the week.

2023-03-28 12:37 UTC, louis-li commented on README.md
Can we add a section how to prepare environment for the code execution? Make it easier to use.

2023-03-28 18:23 UTC, louis-li approved these changes

2023-03-28 18:52 UTC, aldelar approved these changes
Thank you @ryubidragonfire for taking care of the suggestions. Looks good. We can easily tune the rest from this new and cleaner structure.

2023-03-28 18:52 UTC, merged